// resources/js/components/marketing/SectionHeading.vue
<script setup lang="ts">
// Eyebrow pill + two-line Sora title (optional lime payoff line) + lead.
withDefaults(
    defineProps<{
        eyebrow?: string;
        title: string;
        accent?: string;
        subtitle?: string;
        align?: 'left' | 'center';
    }>(),
    { eyebrow: '', accent: '', subtitle: '', align: 'left' },
);
</script>

<template>
    <div :class="align === 'center' ? 'mx-auto max-w-2xl text-center' : 'max-w-2xl'">
        <span v-if="eyebrow" class="ds-badge ds-badge--neutral font-body">
            {{ eyebrow }}
        </span>
        <h2
            class="mt-4 font-display text-3xl font-bold tracking-tight text-balance text-fg sm:text-4xl"
            style="letter-spacing: -0.02em; line-height: 1.12"
        >
            {{ title }}
            <span v-if="accent" style="color: var(--lime-400)">{{ accent }}</span>
        </h2>
        <p
            v-if="subtitle"
            class="mt-4 text-base text-pretty text-fg-muted sm:text-lg"
            style="line-height: 1.6"
        >
            {{ subtitle }}
        </p>
    </div>
</template>

// docs/design_system/components/content/SectionHeading.jsx
import React from 'react';

export function SectionHeading({
  eyebrow, title, highlight, lead, align = 'center', highlightTone = 'lime', style, ...rest
}) {
  const hlColor = highlightTone === 'lime' ? 'var(--lime-400)' : 'var(--emerald-500)';
  return (
    <div
      style={{
        display: 'flex', flexDirection: 'column',
        alignItems: align === 'center' ? 'center' : 'flex-start',
        textAlign: align, maxWidth: align === 'center' ? 640 : undefined,
        margin: align === 'center' ? '0 auto' : undefined,
        ...style,
      }}
      {...rest}
    >
      {eyebrow}
      <h2 style={{
        fontFamily: 'var(--font-display)', fontWeight: 600,
        fontSize: 'clamp(28px, 4vw, 40px)', lineHeight: 1.14,
        letterSpacing: 'var(--ls-tight)', color: 'var(--text-primary)',
        margin: eyebrow ? '18px 0 0' : 0, textWrap: 'balance',
      }}>
        {title}
        {highlight && <><br /><span style={{ color: hlColor }}>{highlight}</span></>}
      </h2>
      {lead && (
        <p style={{
          fontFamily: 'var(--font-body)', fontSize: 17, lineHeight: 1.6,
          color: 'var(--text-secondary)', margin: '16px 0 0', textWrap: 'pretty',
        }}>{lead}</p>
      )}
    </div>
  );
}
